# Generated by Django 4.1a1 on 2022-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('webshell_url', models.CharField(max_length=255)),
                ('webshell_key', models.CharField(max_length=255)),
                ('webshell_passwd', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
